### ISSUE TITLE
Key D39DC0E3 does not exist on hkp://keys.gnupg.net

### ISSUE THREAD

**Issue by arojoal** [maestrodev/puppet-rvm#100]
When provisioning I get this message: Key D39DC0E3 does not exist on hkp://keys.gnupg.net
Notice: /Stage[main]/Rvm::System/Exec[system-rvm]: Dependency Gnupg_key[rvm_D39DC0E3] has failures: true

**Comment by carlossg** [comment]
that's probably a temporary error

**Comment by arojoal** [comment]
You're right, it is working know.

**Comment by evserykh** [comment]
I'm using puppet (3.8.5) and maestrodev-rvm (v1.13.1) and have this error

**Comment by TJM** [comment]
Is there, by chance a firewall that might be blocking "uncommon" ports (like hkp on port 11371/tcp). The key is on the keyserver for sure. http://keys.gnupg.net/pks/lookup?op=get&search=0x3804BB82D39DC0E3

You can try using http:// instead, which goes through a proxy easier (if needed)
