### ISSUE TITLE
Connection timed out to hkp://keys.gnupg.net (firewall)

### ISSUE THREAD

**Issue by TJM** [maestrodev/puppet-rvm#105]
Behind a corporate firewall, sometimes crazy ass ports such as the HKP protocol port (11371) are not open. You end up with a message similar to:

```
# gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3 
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: keyserver timed out
gpg: keyserver receive failed: Keyserver error
```

A simple workaround is to use HKPS (uses port 443), which has the added bonus of being more secure...

```
[root@pt-test-01 ~]# gpg --keyserver hkps://keys.gnupg.net --recv-keys D39DC0E3 
gpg: requesting key D39DC0E3 from hkps server keys.gnupg.net
gpgkeys: HTTP fetch error 60: Peer's Certificate issuer is not recognized.
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

... but alas, they don't have a trusted SSL certificate, so much for security. They also mentioned you could use port 80 like:

```
[root@pt-test-01 ~]# gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys D39DC0E3 
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

So, does anyone have any objections to changing the port to 80 for the GPG stuff?

**Comment by tarrantmarshall** [comment]
$key_server is a parameter on the rvm class which can be customised to be hkps://keys.gnupg.net:80
works for me.

**Comment by TJM** [comment]
Thanks @tarrantmarshall , I am not sure hkps and port 80 go together, but if it worked for you, I guess its good. I was more or less suggesting that the default could be the port 80 URL rather than the silly 11371 port. And looking for feedback. Thanks, I sortof forgot about the parameter :).
