### ISSUE TITLE
Can puppet-gvm or maybe puppet-npm be a thing?

### ISSUE THREAD

**Issue by jyaworski** [maestrodev/puppet-rvm#121]
Hello:

This module seems like it could be very easily adapted/copied into a module for npm or gvm. Is that something that maestrodev would be interested in doing, or would you prefer a fork?

**Comment by carlossg** [comment]
I wouldn't do it, you can fork

**Comment by jyaworski** [comment]
@carlossg if we did fork @voxpupuli, would you prefer we fork directly, or just copy and paste into a new repo?

**Comment by carlossg** [comment]
I don't really care
