### ISSUE TITLE
passenger_mod.so missing?

### ISSUE THREAD

**Issue by BroiSatse** [maestrodev/puppet-rvm#54]
I am having an issue with install-passenger-apache2-module on vagrant box. Logs says that this stup executed successfully, however there is no buildout folder in passenger gem path and apache fails to start due to missing passenger_mod.so file. I'm sorry if I missed sth obvious but I am just starting puppet and I am trying to figure it out for couple of days already.

Vagrantfile:

     # -*- mode: ruby -*-
     # vi: set ft=ruby :
    VAGRANTFILE_API_VERSION = "2"

     Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

       config.vm.box = "ubuntu14.04"
       config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
       config.vm.define 'backend' do |backend|
         backend.vm.provider :virtualbox do |v|
           v.memory = 2048
         end
         backend.vm.provision :puppet do |puppet|
           puppet.manifest_file  = "backend.pp"
           puppet.module_path = "../puppet/modules"
           puppet.options = "--verbose --debug"
         end
      end
    end

Manifest:

     include rvm

     stage {'init':
       before => Stage['main'],
     }

     class {'apt': 
       always_apt_update => true,
       stage  => 'init',
     }

     rvm_system_ruby {
       'ruby-2.1.1':
         ensure      => present,
         default_use => true,
     }

     rvm_gemset {
       'ruby-2.1.1@myapp':
         ensure => present,
         require => Rvm_system_ruby['ruby-2.1.1']
     }

     rvm_gem {
       'ruby-2.1.1@myapp/bundler':
         ensure => present,
         require => Rvm_gemset['ruby-2.1.1@myapp'],
     }

     class { 'apache': }
     class { 'rvm::passenger::apache':
         version            => '4.0.48',
         ruby_version       => 'ruby-2.1.1',
        mininstances       => '3',
         maxinstancesperapp => '0',
         maxpoolsize        => '30',
         spawnmethod        => 'smart-lv2',
     }

Log file (without --debug --verbose for simplicity):

     Bringing machine 'backend' up with 'virtualbox' provider...
     ==> backend: Importing base box 'ubuntu14.04'...

     [KProgress: 90%
     [K==> backend: Matching MAC address for NAT networking...
     ==> backend: Setting the name of the VM: Backend_backend_1408140661365_20892
     ==> backend: Clearing any previously set forwarded ports...
     ==> backend: Clearing any previously set network interfaces...
     ==> backend: Preparing network interfaces based on configuration...
         backend: Adapter 1: nat
     ==> backend: Forwarding ports...
         backend: 22 => 2222 (adapter 1)
     ==> backend: Running 'pre-boot' VM customizations...
     ==> backend: Booting VM...
     ==> backend: Waiting for machine to boot. This may take a few minutes...
         backend: SSH address: 127.0.0.1:2222
         backend: SSH username: vagrant
         backend: SSH auth method: private key
         backend: Warning: Connection timeout. Retrying...
         backend: Warning: Remote connection disconnect. Retrying...
     ==> backend: Machine booted and ready!
     GuestAdditions 4.3.10 running --- OK.
     ==> backend: Checking for guest additions in VM...
     ==> backend: Mounting shared folders...
         backend: /vagrant => /home/broisatse/Work/BeeOrganised/Backend
         backend: /tmp/vagrant-puppet-2/manifests => /home/broisatse/Work/BeeOrganised/Backend/manifests
         backend: /tmp/vagrant-puppet-2/modules-0 => /home/broisatse/Work/BeeOrganised/puppet/modules
     ==> backend: Running provisioner: puppet...
     ==> backend: Running Puppet with backend.pp...
     ==> backend: stdin: is not a tty
     ==> backend: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
     ==> backend: Notice: Compiled catalog for vagrant-ubuntu-trusty-64.mynet in environment production in 2.60 seconds
     ==> backend: Notice: /Stage[init]/Apt::Update/Exec[apt_update]/returns: executed successfully
     ==> backend: Notice: /Stage[main]/Concat::Setup/File[/var/lib/puppet/concat]/ensure: created
     ==> backend: Notice: /Stage[main]/Concat::Setup/File[/var/lib/puppet/concat/bin]/ensure: created
     ==> backend: Notice: /Stage[main]/Concat::Setup/File[/var/lib/puppet/concat/bin/concatfragments.sh]/ensure: defined content as '{md5}7bbe7c5fce25a5ddd20415d909ba44fc'
     ==> backend: Notice: /Stage[main]/Rvm::Group/Group[rvm]/ensure: created
     ==> backend: Notice: /Stage[main]/Rvm::Rvmrc/File[/etc/rvmrc]/ensure: defined content as '{md5}3ec590d219afbf91a7c1a149a15e72cb'
     ==> backend: Notice: /Stage[main]/Rvm::Passenger::Dependencies::Ubuntu/Package[libcurl4-gnutls-dev]/ensure: ensure changed 'purged' to 'present'
     ==> backend: Notice: /Stage[main]/Apache/Package[httpd]/ensure: ensure changed 'purged' to 'present'
     ==> backend: Notice: /Stage[main]/Apache/Exec[mkdir /etc/apache2/conf.d]/returns: executed successfully
     ==> backend: Notice: /Stage[main]/Apache/File[/etc/apache2/apache2.conf]/content: content changed '{md5}da32fcc6a783acaebf0d74c17c726bf7' to '{md5}9e1ef21e638936a330d4a4ce36582d14'
     ==> backend: Notice: /Stage[main]/Apache::Dev/Package[libapr1-dev]/ensure: ensure changed 'purged' to 'present'
     ==> backend: Notice: /Stage[main]/Apache/File[/etc/apache2/sites-enabled/000-default.conf]/ensure: removed
     ==> backend: Notice: /Stage[main]/Apache::Dev/Package[apache2-prefork-dev]/ensure: ensure changed 'purged' to 'present'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Mime/Apache::Mod[mime]/File[mime.load symlink]/target: target changed '../mods-available/mime.load' to '/etc/apache2/mods-available/mime.load'
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_groupfile]/File[authz_groupfile.load]/content: content changed '{md5}97a3e14926ce7bf5f2d2a7b93ece648d' to '{md5}bf972e82336c72b20d67d871ef77d4ce'
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_groupfile]/File[authz_groupfile.load symlink]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_user]/File[authz_user.load]/content: content changed '{md5}bcf988f105564ec1e14b78df56a01cd8' to '{md5}69150f8246499e0135580d8cc16eaeab'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Mime/File[mime.conf]/content: content changed '{md5}7369c2fd5edf2192edbd6d865b632ae5' to '{md5}2fa646fe615e44d137a5d629f868c107'
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[access_compat]/File[access_compat.load]/content: content changed '{md5}f7f77b3eb4005749b583ff14b49f8bf1' to '{md5}a3e92887d86700b30a3869d0e8c159d7'
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[access_compat]/File[access_compat.load symlink]/target: target changed '../mods-available/access_compat.load' to '/etc/apache2/mods-available/access_compat.load'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Setenvif/File[setenvif.conf]/content: content changed '{md5}533f5f92761c2c24d6820f1d7d1c45ad' to '{md5}c7ede4173da1915b7ec088201f030c28'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Deflate/File[deflate.conf]/content: content changed '{md5}6649a32153b9afdc53f6898b5a10a2d6' to '{md5}44d54f557a5612be8da04c49dd6da862'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Negotiation/File[negotiation.conf]/content: content changed '{md5}443398efdd41085bc1a70047f6e61c95' to '{md5}47284b5580b986a6ba32580b6ffb9fd7'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Negotiation/Apache::Mod[negotiation]/File[negotiation.conf symlink]/target: target changed '../mods-available/negotiation.conf' to '/etc/apache2/mods-available/negotiation.conf'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Alias/Apache::Mod[alias]/File[alias.load symlink]/target: target changed '../mods-available/alias.load' to '/etc/apache2/mods-available/alias.load'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Dir/File[dir.conf]/content: content changed '{md5}fe4bc5fa3b3cc7a241fe57f8fabc55a1' to '{md5}c741d8ea840e6eb999d739eed47c69d7'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Dir/Apache::Mod[dir]/File[dir.conf symlink]/target: target changed '../mods-available/dir.conf' to '/etc/apache2/mods-available/dir.conf'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Setenvif/Apache::Mod[setenvif]/File[setenvif.load symlink]/target: target changed '../mods-available/setenvif.load' to '/etc/apache2/mods-available/setenvif.load'
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[auth_basic]/File[auth_basic.load]/content: content changed '{md5}a92c34a3ce5e67e2ecbd272155ebe072' to '{md5}5eec35bb52e1ae9ff5eec602ed1d2374'
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[auth_basic]/File[auth_basic.load symlink]/target: target changed '../mods-available/auth_basic.load' to '/etc/apache2/mods-available/auth_basic.load'
     ==> backend: Notice: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments.concat.out]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[authn_file]/File[authn_file.load symlink]/target: target changed '../mods-available/authn_file.load' to '/etc/apache2/mods-available/authn_file.load'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Dav/Apache::Mod[dav]/File[dav.load symlink]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments.concat]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Mod::Dir/Apache::Mod[dir]/File[dir.load symlink]/target: target changed '../mods-available/dir.load' to '/etc/apache2/mods-available/dir.load'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Mime/Apache::Mod[mime]/File[mime.conf symlink]/target: target changed '../mods-available/mime.conf' to '/etc/apache2/mods-available/mime.conf'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Dav_fs/Apache::Mod[dav_fs]/File[dav_fs.load]/content: content changed '{md5}17f662fd023dbaaab9d89f9a11ae58c1' to '{md5}3fa14d6e9f9d8eb25d09ed4823508f6d'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Dav_fs/Apache::Mod[dav_fs]/File[dav_fs.load symlink]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Mod::Alias/File[alias.conf]/content: content changed '{md5}c6e9f26152898c38e58211c8b362d5c3' to '{md5}cb528041df274fb077800a8e2e64f94e'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Alias/Apache::Mod[alias]/File[alias.conf symlink]/target: target changed '../mods-available/alias.conf' to '/etc/apache2/mods-available/alias.conf'
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_core]/File[authz_core.load symlink]/target: target changed '../mods-available/authz_core.load' to '/etc/apache2/mods-available/authz_core.load'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Negotiation/Apache::Mod[negotiation]/File[negotiation.load symlink]/target: target changed '../mods-available/negotiation.load' to '/etc/apache2/mods-available/negotiation.load'
     ==> backend: Notice: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache/Apache::Vhost[default]/Apache::Listen[80]/Concat::Fragment[Listen 80]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments/10_Listen 80]/ensure: defined content as '{md5}d5fcefc335117f400d451de47efeca87'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Reqtimeout/File[reqtimeout.conf]/content: content changed '{md5}40b45155afb3d14263d12e6fc4a98513' to '{md5}81c51851ab7ee7942bef389dc7c0e985'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Reqtimeout/Apache::Mod[reqtimeout]/File[reqtimeout.conf symlink]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Mod::Reqtimeout/Apache::Mod[reqtimeout]/File[reqtimeout.load symlink]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache/File[/etc/apache2/sites-available/default-ssl.conf]/ensure: removed
     ==> backend: Notice: /Stage[main]/Apache::Mod::Setenvif/Apache::Mod[setenvif]/File[setenvif.conf symlink]/target: target changed '../mods-available/setenvif.conf' to '/etc/apache2/mods-available/setenvif.conf'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Deflate/Apache::Mod[deflate]/File[deflate.conf symlink]/target: target changed '../mods-available/deflate.conf' to '/etc/apache2/mods-available/deflate.conf'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Deflate/Apache::Mod[deflate]/File[deflate.load]/content: content changed '{md5}6a7a23153796456ee919abdf728fd972' to '{md5}ac4540dd672556b07f900425751f745c'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Deflate/Apache::Mod[deflate]/File[deflate.load symlink]/target: target changed '../mods-available/deflate.load' to '/etc/apache2/mods-available/deflate.load'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Autoindex/Apache::Mod[autoindex]/File[autoindex.load symlink]/target: target changed '../mods-available/autoindex.load' to '/etc/apache2/mods-available/autoindex.load'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Autoindex/File[autoindex.conf]/content: content changed '{md5}bfba7d77669e02b869b92e98215d58fc' to '{md5}2421a3c6df32c7e38c2a7a22afdf5728'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Autoindex/Apache::Mod[autoindex]/File[autoindex.conf symlink]/target: target changed '../mods-available/autoindex.conf' to '/etc/apache2/mods-available/autoindex.conf'
     ==> backend: Notice: /Stage[main]/Apache/Concat::Fragment[Apache ports header]/File[/var/lib/puppet/concat/_etc_apache2_ports.conf/fragments/10_Apache ports header]/ensure: defined content as '{md5}afe35cb5747574b700ebaa0f0b3a626e'
     ==> backend: Notice: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/Exec[concat_/etc/apache2/ports.conf]/returns: executed successfully
     ==> backend: Notice: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/Exec[concat_/etc/apache2/ports.conf]: Triggered 'refresh' from 4 events
     ==> backend: Notice: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/etc/apache2/ports.conf]/content: content changed '{md5}a961f23471d985c2b819b652b7f64321' to '{md5}334fa5cddbf9a408ea1ca7a1666b1fc4'
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_host]/File[authz_host.load]/content: content changed '{md5}f529587409471e3feb62256bccaf538a' to '{md5}4b8162e3e3a58d1dc2222e2ad352bd93'
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_host]/File[authz_host.load symlink]/target: target changed '../mods-available/authz_host.load' to '/etc/apache2/mods-available/authz_host.load'
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[filter]/File[filter.load symlink]/target: target changed '../mods-available/filter.load' to '/etc/apache2/mods-available/filter.load'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Worker/Apache::Mpm[worker]/File[/etc/apache2/mods-available/worker.load]/ensure: defined content as '{md5}3064ef75f030fbf76986f6f073beb113'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Worker/Apache::Mpm[worker]/File[/etc/apache2/mods-enabled/worker.load]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Mod::Worker/File[/etc/apache2/mods-available/worker.conf]/ensure: defined content as '{md5}8b152143a27f5bf9aafdcd81059ea91c'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Worker/Apache::Mpm[worker]/File[/etc/apache2/mods-enabled/worker.conf]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Mod::Cgid/File[cgid.conf]/content: content changed '{md5}e8a2836392051bde889cf9c137058273' to '{md5}7dffbb5823bcbb9ab4d3e67ab14d38a0'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Cgid/Apache::Mod[cgid]/File[cgid.conf symlink]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Mod::Cgid/Apache::Mod[cgid]/File[cgid.load symlink]/ensure: created
     ==> backend: Notice: /Stage[main]/Rvm::System/Exec[system-rvm]/returns: executed successfully
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[env]/File[env.load symlink]/target: target changed '../mods-available/env.load' to '/etc/apache2/mods-available/env.load'
     ==> backend: Notice: /Stage[main]/Apache/File[/etc/apache2/sites-available/000-default.conf]/ensure: removed
     ==> backend: Notice: /Stage[main]/Apache/Apache::Vhost[default]/File[15-default.conf]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache/Apache::Vhost[default]/File[15-default.conf symlink]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Mod::Dav_fs/File[dav_fs.conf]/content: content changed '{md5}162db96239f13b5416f369b6306d9db6' to '{md5}e36e2951cff0d4df331652ca6fccdb77'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Dav_fs/Apache::Mod[dav_fs]/File[dav_fs.conf symlink]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Default_mods/Apache::Mod[authz_user]/File[authz_user.load symlink]/target: target changed '../mods-available/authz_user.load' to '/etc/apache2/mods-available/authz_user.load'
     ==> backend: Notice: /Stage[main]/Main/Rvm_system_ruby[ruby-2.1.1]/ensure: created
     ==> backend: Notice: /Stage[main]/Rvm::Passenger::Gem/Rvm_gem[passenger]/ensure: created
     ==> backend: Notice: /Stage[main]/Rvm::Passenger::Apache/Exec[passenger-install-apache2-module]/returns: executed successfully
     ==> backend: Notice: /Stage[main]/Apache::Mod::Passenger/File[passenger.conf]/ensure: defined content as '{md5}3655800b46fe71316ec3afbff6f3cd7a'
     ==> backend: Notice: /Stage[main]/Main/Rvm_gemset[ruby-2.1.1@bee_organised]/ensure: created
     ==> backend: Notice: /Stage[main]/Apache::Mod::Passenger/Apache::Mod[passenger]/Package[libapache2-mod-passenger]/ensure: ensure changed 'purged' to 'present'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Passenger/Apache::Mod[passenger]/File[passenger.load]/content: content changed '{md5}61421ba3247d368cfe99b540ad4ebc98' to '{md5}0832bae2588468ab7570b34ed77ef075'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Passenger/Apache::Mod[passenger]/File[passenger.load symlink]/target: target changed '../mods-available/passenger.load' to '/etc/apache2/mods-available/passenger.load'
     ==> backend: Notice: /Stage[main]/Apache::Mod::Passenger/Apache::Mod[passenger]/File[passenger.conf symlink]/target: target changed '../mods-available/passenger.conf' to '/etc/apache2/mods-available/passenger.conf'
     ==> backend: Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/mpm_event.conf]/ensure: removed
     ==> backend: Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/authn_core.load]/ensure: removed
     ==> backend: Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/status.load]/ensure: removed
     ==> backend: Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/status.conf]/ensure: removed
     ==> backend: Notice: /Stage[main]/Apache/File[/etc/apache2/mods-enabled/mpm_event.load]/ensure: removed
     ==> backend: Notice: /Stage[main]/Rvm::Passenger::Apache/Exec[copy passenger_extra.conf to passenger.conf]/returns: executed successfully
     ==> backend: Error: /Stage[main]/Apache::Service/Service[httpd]: Failed to call refresh: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1: 
     ==> backend: Error: /Stage[main]/Apache::Service/Service[httpd]: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1: 
     ==> backend: Notice: Finished catalog run in 601.50 seconds

**Comment by jonoterc** [comment]
I'm encountering this problem as well

The first issue is not with this module, but (apparently) with puppet labs' apache module on 14.04, which (maybe only in this context?) is getting configured with multiple mpm modules ("event" and "worker"), which passenger-install-apache2-module detects as a broken install and exits early.  

A secondary issue is that 14.04 does *not* install a passenger_extra.conf file, unlike 12.04.

I'm working on PR to address the latter issue.  

Also, as part of that I'm thinking of adding a file declaration to verify that the mod_passenger.so object file exists; because exec can return a successful result when a called script fails, I'm thinking this would be a simple way to call attention to the fact passenger-install-apache2-module exec failed (despite what appears to the the case in the logs).

**Comment by jonoterc** [comment]
Just to be clear regarding the mpm_issue, I'm avoiding the conflict by changing:

    class { 'apache': }
to

    class { 'apache':
      mpm_module => 'event',
    }

Otherwise, apache (on Ubuntu 14.04) is installed with both the event and worker MPM modules, which prevents it from even starting up.
