### ISSUE TITLE
Suggest using the forge approved module for gpg

### ISSUE THREAD

**Issue by edestecd** [maestrodev/puppet-rvm#86]
I propose we swap the exec being used for gpg key management with a module.
This module would probably do the trick.  It can handle the key import as well as installing gpg, if needed.
https://forge.puppetlabs.com/golja/gnupg

**Comment by edestecd** [comment]
We may need to get a fact added to that module that indicates if gpg is installed.
Other than that, It looks like it can provide the same functionality.

**Comment by carlossg** [comment]
It's a bit tricky because I don't think gpg should be installed in this module.
So maybe it is just a matter of documentation to add to the readme "install gpg and this key before rvm" or conditionals to check if the gpg module is present

**Comment by edestecd** [comment]
I agree about installing gpg.  It should not be installed by this module, if not present already.
I suggest removing the gpg.pp class and adding to the readme to use the above mentioned module, if you want to install gpg.

However, I do think it is appropriate to add the key, if gpg is detected, to prevent rvm from failing.
I suggest depending on the above mentioned module to manage this as opposed to the current exec...
If you agree, I can submit a patch to https://forge.puppetlabs.com/golja/gnupg that includes a fact for detecting if gpg is installed.

**Comment by edestecd** [comment]
I also think it might be nice if managing the key was optional, and had a param to turn it off...

**Comment by edestecd** [comment]
I have added facts for gnupg detection.
https://github.com/n1tr0g/golja-gnupg/pull/8/files

**Comment by n1tr0g** [comment]
Hey guys I am joining the party :+1: 

So yeah if you want to make your module dependent on mine and you think it will make it work better,  I am happy to add the new facters.

**Comment by TJM** [comment]
GPG Should, in fact, be installed by the "gnupg" module, and the keys should also be managed by the "gnupg" module. A module should do one thing and do it well. "This" module should not be trying to determine if gpg is installed and if so, managing the key. I would recommend just requiring the "gnupg" module and installing gpg on any platform that is supported by it. It is a *GOOD THING* :)

**Comment by carlossg** [comment]
I don't think this module should install gpg nor call the gnupg module to install it. It is not required by RVM and it should be defined at a host level, not here.
Now about adding the gpg key, I'm not sure whether this module should install it, or just document how to do it with the gnupg module.

**Comment by TJM** [comment]
On second thought, I agree with @carlossg. This module should *document* the use of the "gnupg" module to install the necessary keys. It should not be doing any GPG management itself.

**Comment by edestecd** [comment]
I agree that the RVM module should not install gpg and that the README should document the use of the gnupg module.  I am torn on the key management, however.  I could be OK with the RVM module managing it or not.

I could see a separate class that manages the key optionally and the default is to not include the class or wrap it in a param.  A good example of this is the elasticsearch module which offers to install java for you with the puppet labs module.  It is off by default and you must install the java module yourself as it is not a dependency in the metadata.json.

elasticsearch example:
https://github.com/elastic/puppet-elasticsearch/blob/master/README.md#java-installation
https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/init.pp#L326

**Comment by carlossg** [comment]
I have added an initial implementation in the gnupg branch

**Comment by carlossg** [comment]
merged
